import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ToastProvider from "../../toast.provider";
const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });
import PropState from "@/app/Data";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PropState>
        <body className={inter.className}>
          <ToastProvider>{children}</ToastProvider>
        </body>
      </PropState>
    </html>
  );
}
